In [ ]:
import pandas as pd

test = pd.read_csv(
    "../data/test_FD001.txt",
    sep=r"\s+",
    header=None
)

test.shape

(13096, 26)

In [8]:
columns = [
    "unit_number",
    "time_cycles",
    "op_setting_1",
    "op_setting_2",
    "op_setting_3",
]

columns += [f"sensor_{i}" for i in range(1, 22)]

test.columns = columns

In [9]:
test.head()

,unit_number,time_cycles,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,521.72,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,522.16,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,521.97,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,521.38,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,522.15,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130

In [10]:
test["unit_number"].nunique()

100

In [13]:
test.groupby("unit_number")["time_cycles"].max().reset_index().head(10)

   unit_number  time_cycles
0            1           31
1            2           49
2            3          126
3            4          106
4            5           98
5            6          105
6            7          160
7            8          166
8            9           55
9           10          192

In [20]:
rul_test = pd.read_csv(
    "../data/RUL_FD001.txt",
    header=None
)

rul_test

      0
0   112
1    98
2    69
3    82
4    91
..  ...
95  137
96   82
97   59
98  117
99   20

[100 rows x 1 columns]

In [22]:
last_cycles = (
    test.groupby("unit_number")["time_cycles"]
    .max()
    .reset_index()
)

last_cycles.columns = ["unit_number", "last_cycle"]

last_cycles["true_RUL"] = rul_test[0]

last_cycles["failure_cycle"] = (
    last_cycles["last_cycle"] + last_cycles["true_RUL"]
)

last_cycles.head(10)

   unit_number  last_cycle  true_RUL  failure_cycle
0            1          31       112            143
1            2          49        98            147
2            3         126        69            195
3            4         106        82            188
4            5          98        91            189
5            6         105        93            198
6            7         160        91            251
7            8         166        95            261
8            9          55       111            166
9           10         192        96            288

In [23]:
test_constant_cols = [
    col for col in test.columns
    if test[col].nunique() <= 1
]

print(test_constant_cols)

['op_setting_3', 'sensor_1', 'sensor_5', 'sensor_10', 'sensor_16', 'sensor_18', 'sensor_19']